[package]
name = "rwifi"
version = "0.1.0"
edition = "2024"

[lib]
name = "rwifi"
paht = "src/lib.rs"

[dependencies]
zbus = { version = "5.6.0", features = ["tokio"], default-features = false }


[dev-dependencies]
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
